name: Save distribution 0xcbcdf9626bc03e24f779434178a73a0b4bad62ed

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'

jobs:
  generate_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch and process LP distribution
      run: |
        python get_distribution.py --pool_id 0xcbcdf9626bc03e24f779434178a73a0b4bad62ed --surround_ticks 300

    - name: Commit and push if there are changes
      run: |
        git add data/0xcbcdf9626bc03e24f779434178a73a0b4bad62ed
        git commit -m "Update data" -a || echo "No changes to commit"
        git push
